# build-bootstrap.ps1
# Generates SCAFFOLD-PIPELINE.md -- a single-file pipeline bootstrap.
#
# Team members copy SCAFFOLD-PIPELINE.md into a fresh empty folder, open Claude Code,
# and say "scaffold from SCAFFOLD-PIPELINE.md". Claude creates all pipeline files
# and writes the compact .claude\CLAUDE.md as the final step.
#
# Why NOT .claude\CLAUDE.md directly:
#   .claude\CLAUDE.md is auto-injected on every turn. A 700+ KB file there would cost
#   thousands of tokens per turn. The bootstrap lives in the workspace root (not auto-loaded),
#   is read exactly once, then replaced by the compact 45-line co-worker CLAUDE.md.
#
# Usage:
#   pwsh agentic-pipeline\scripts\build-bootstrap.ps1 [-WorkspaceRoot .] [-OutputPath SCAFFOLD-PIPELINE.md]
#
# Inputs:  dist/ folder (all pipeline files)
# Outputs: SCAFFOLD-PIPELINE.md (workspace root)
#          dist\SCAFFOLD-PIPELINE.md (copy for distribution)

param(
    [string]$WorkspaceRoot = ".",
    [string]$OutputPath    = "SCAFFOLD-PIPELINE.md"
)

$DistPath = (Resolve-Path (Join-Path $WorkspaceRoot "dist")).Path
if (-not (Test-Path $DistPath)) {
    Write-Error "dist/ folder not found at $DistPath. Run from the poc-workspace root."
    exit 1
}

# Files excluded from the manifest:
#   README.md               -- human-readable docs, not pipeline operation files
#   package-lock.json       -- generated by npm install; no need to distribute
#   build-design-reference.py -- optional .docx generator, not needed for pipeline operation
#   SCAFFOLD-PIPELINE.md    -- the output file itself (avoid embedding a stale copy)
#   .claude/settings.json   -- machine-specific (hardcoded paths); distribute .example only
$excludeNames = @("README.md", "package-lock.json", "build-design-reference.py", "SCAFFOLD-PIPELINE.md", "settings.json")

# Path-prefix exclusions (relative to dist root, forward-slash normalised):
#   .claude/kb/core/  -- local personal KBs (master-arch, fiserv-arch, cost-optimizer skills)
#                        MUST NOT be distributed. Users supply their own KBs.
$excludePrefixes = @(".claude/kb/core/")

# Compact CLAUDE.md -- written as the LAST scaffolding step (replaces bootstrap in future sessions)
$compactClaudePath = Join-Path $DistPath ".claude\CLAUDE.md"
if (-not (Test-Path $compactClaudePath)) {
    Write-Error ".claude\CLAUDE.md not found in dist/. Run sync first."
    exit 1
}
$compactClaude = (Get-Content -Path $compactClaudePath -Raw -Encoding UTF8) -replace "`r`n", "`n"

# ---- File count for reporting ----
$allFiles = Get-ChildItem -Path $DistPath -Recurse -File |
    Where-Object {
        $relPath = $_.FullName.Substring($DistPath.Length + 1).Replace("\", "/")
        $_.Name -notin $excludeNames `
        -and $relPath -ne ".claude/CLAUDE.md" `
        -and -not ($excludePrefixes | Where-Object { $relPath.StartsWith($_) })
    } |
    Sort-Object FullName
$totalFiles = $allFiles.Count + 1  # +1 for compact CLAUDE.md

$today = Get-Date -Format "yyyy-MM-dd"

# ================================================================
# HEADER -- instructions for both humans and Claude
# ================================================================
$header = @"
# Agentic Delivery Pipeline -- Single-File Bootstrap
<!--
  Generated:  $today
  Generator:  agentic-pipeline/scripts/build-bootstrap.ps1
  Files:      $totalFiles pipeline files embedded
  Size:       $(  [math]::Round( ($allFiles | Measure-Object -Property Length -Sum).Sum / 1KB, 0 )  ) KB source

  WHAT THIS FILE IS
  A self-contained bootstrap for the Agentic Delivery Pipeline.
  Drop it in a fresh empty folder, open Claude Code, and say "scaffold from SCAFFOLD-PIPELINE.md".
  Claude reads this file once, creates all pipeline files, and writes a compact .claude\CLAUDE.md
  for all future sessions. The bootstrap file is not loaded again after that.

  HOW TO USE (4 steps)
  1. Create a new empty folder:  C:\MyWork\my-project\
  2. Copy SCAFFOLD-PIPELINE.md into that folder.
  3. Open Claude Code in that folder:  cd C:\MyWork\my-project && claude
  4. Say:  scaffold from SCAFFOLD-PIPELINE.md

  WHAT CLAUDE DOES
  - Creates all directories and writes ~$totalFiles files (agents, hooks, scripts, KBs, config)
  - Writes .claude\CLAUDE.md last (compact co-worker instructions for all future sessions)
  - Reports two manual remaining steps (workspace-config + settings.local.json)

  AFTER SCAFFOLDING -- two manual steps
  1. cp agentic-pipeline\workspace-config.sample.json agentic-pipeline\workspace-config.json
     Edit workspace-config.json and set "workspaceRoot" to your absolute folder path.
  2. cp .claude\settings.local.json.template .claude\settings.local.json
     Edit settings.local.json and replace WORKSPACE_ROOT_PATH with the same absolute path.
  Then say "Activate Sprint Manager" to begin your first sprint.

  NOT INCLUDED (proprietary / machine-specific)
  .claude\kb\master-arch-coworker.md  -- project-specific architecture KB
  .claude\kb\fiserv-arch-coworker.md  -- Fiserv platform KB
  Obtain from your team repo and drop into .claude\kb\ manually.
  The pipeline runs without them; agents reference them for architecture questions only.

  REGENERATING THIS FILE
  After pipeline updates, regenerate from the source workspace:
    pwsh agentic-pipeline\scripts\build-bootstrap.ps1 -WorkspaceRoot . -OutputPath SCAFFOLD-PIPELINE.md
-->

---

## SCAFFOLD COMMAND

When the user says **"scaffold from SCAFFOLD-PIPELINE.md"**, **"scaffold"**, or **"setup pipeline"**,
execute this procedure exactly — and ONLY when explicitly asked:

1. Read SCAFFOLD-PIPELINE.md to locate the SCAFFOLD MANIFEST section.
2. For every block between `=== FILE: <path> ===` and `=== END FILE ===`:
   - Extract the relative path from the opening delimiter line.
   - Extract the raw content between the two delimiters (preserve exact whitespace and line endings).
   - Create any missing parent directories.
   - Write the file at that relative path from the current working directory.
   - Skip `.claude/CLAUDE.md` — that is handled by step 3.
3. Write `.claude/CLAUDE.md` using the content between `=== COMPACT_CLAUDE_MD ===` and
   `=== END COMPACT_CLAUDE_MD ===` at the bottom of this file.
4. Report success. Tell the user:

```
Pipeline scaffolded. $totalFiles files created.

Two manual steps remaining:
  1. Copy agentic-pipeline\workspace-config.sample.json
          -> agentic-pipeline\workspace-config.json
     Set "workspaceRoot" to this folder's absolute path.

  2. Copy .claude\settings.local.json.template
          -> .claude\settings.local.json
     Replace WORKSPACE_ROOT_PATH with the same absolute path.

Say "Activate Sprint Manager" to begin your first sprint.
```

Do NOT scaffold unless the user explicitly asks. Until asked, use this file's content
to answer questions about the pipeline.

---

<!-- ============================================================ -->
<!-- SCAFFOLD MANIFEST                                             -->
<!-- One block per file. Delimiter lines are guaranteed unique --  -->
<!-- no pipeline file contains the literal string                  -->
<!-- "=== FILE:" or "=== END FILE ===" in its body.               -->
<!-- ============================================================ -->

"@

# ================================================================
# MANIFEST BODY -- one block per file
# ================================================================
$manifest = ""
$embeddedCount = 0

foreach ($file in $allFiles) {
    $relPath = $file.FullName.Substring($DistPath.Length + 1).Replace("\", "/")
    $content = (Get-Content -Path $file.FullName -Raw -Encoding UTF8) -replace "`r`n", "`n"
    if ($null -eq $content) { $content = "" }

    $manifest += "=== FILE: $relPath ===`n$content`n=== END FILE ===`n`n"
    $embeddedCount++
}

# ================================================================
# COMPACT CLAUDE.MD -- written last, replaces this bootstrap file
# ================================================================
$footer = @"

<!-- ============================================================ -->
<!-- COMPACT_CLAUDE_MD                                            -->
<!-- Written as .claude\CLAUDE.md on the FINAL scaffolding step.  -->
<!-- ~45 lines. Auto-loaded by Claude Code on every future turn.  -->
<!-- The large manifest above is NOT loaded again after this.     -->
<!-- ============================================================ -->

=== COMPACT_CLAUDE_MD ===
$compactClaude
=== END COMPACT_CLAUDE_MD ===
"@

$fullContent = $header + $manifest + $footer

# ================================================================
# WRITE OUTPUT
# ================================================================
$rootResolved = (Resolve-Path $WorkspaceRoot).Path
$outputFull   = Join-Path $rootResolved $OutputPath
[System.IO.File]::WriteAllText($outputFull, $fullContent, [System.Text.Encoding]::UTF8)
$sizeKB = [math]::Round((Get-Item $outputFull).Length / 1KB, 0)

# Also copy to dist/ for distribution alongside README.md
$distCopy = Join-Path $DistPath $OutputPath
[System.IO.File]::WriteAllText($distCopy, $fullContent, [System.Text.Encoding]::UTF8)

Write-Host "Generated: $outputFull  ($sizeKB KB, $embeddedCount files + compact CLAUDE.md)"
Write-Host "  Dist copy: $distCopy"
Write-Host ""
Write-Host "Share SCAFFOLD-PIPELINE.md with your team."
Write-Host "They drop it in a fresh folder, open Claude Code, and say:"
Write-Host "  scaffold from SCAFFOLD-PIPELINE.md"
