/**
 * t009.spec.ts — FE Test Plan Spec Scaffolding
 * Sprint: sprint-01 | Generated by: A-07 (T-009)
 * A-04 copies this to app/frontend/src/test/ during T-004
 * seed.ts pending — A-05 writes factories during T-005
 */
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── RC-001 / CI-001: Navigation Menu ────────────────────────────────────────
describe('RC-001 Navigation Menu', () => {
  it('TC-FE-001: renders all top-level sections; active item has nav-item--active class', () => {
    // arrange: render AppSidebar with 9 top-level sections; currentRoute="/journal-entry"
    // act: render(<AppSidebar navItems={mockNavItems} currentRoute="/journal-entry" />)
    expect(screen.getByText('Journal Entry Financial & Statistical').closest('[class*="nav-item"]'))
      .toHaveClass('nav-item--active');
  });

  it('TC-FE-002: alert dot appears when alertState="dot"; absent when alertState="none"', () => {
    // arrange: render with one alertState="dot" item, one alertState="none" item
    // act: render(<AppSidebar navItems={mixedAlertItems} currentRoute="/" />)
    expect(document.querySelectorAll('.nav-alert-dot').length).toBe(1);
  });

  it('TC-FE-003: section expands on click; sub-items visible; collapses on second click; expand < 200ms', async () => {
    // arrange: Playwright e2e — app loaded, "Journal Entry Processing" collapsed
    // act: page.click('[data-nav-id="je-processing"]')
    expect(true).toBe(true); // placeholder — Playwright spec in e2e/navigation.spec.ts
  });

  it('TC-FE-004: all nav items keyboard-reachable; active item has aria-current="page"; zero axe violations', async () => {
    // arrange: render AppSidebar; axe-core imported
    // act: run axe analysis on nav element
    expect(screen.getByRole('link', { current: 'page' }).textContent).toBe('Journal Entry Financial & Statistical');
  });
});

// ─── RC-002 / CI-002: View JE Header ─────────────────────────────────────────
describe('RC-002 View Journal Entry Header', () => {
  it('TC-FE-005: all 16 fields rendered; optional empty fields shown (not hidden)', () => {
    // arrange: render JournalEntryHeader with unpostedJE (autoReversalDate: null)
    // act: render(<JournalEntryHeader journalEntry={unpostedJE} />)
    expect(screen.getByText('Auto Reversal Date')).toBeInTheDocument();
  });

  it('TC-FE-006: unposted → amber badge + empty post fields; posted → green badge + populated post fields', () => {
    // arrange: render with postedJE
    // act: render(<JournalEntryHeader journalEntry={postedJE} />)
    expect(screen.getByText('Posted')).toHaveClass('badge-posted');
    expect(screen.getByLabelText('Posted Date/Time').textContent).toBe('2026-05-23T12:00:00Z');
  });

  it('TC-FE-007: all read-only field labels associated via accessible markup; zero axe violations', async () => {
    // arrange: render JournalEntryHeader; run axe-core
    // act: const results = await axe(container)
    expect(true).toBe(true); // axe result: results.violations.length === 0
  });

  it('TC-FE-008: unposted badge pixel-matches amber baseline; posted badge pixel-matches green baseline', () => {
    // arrange: Playwright visual test — screenshot of StatusBadge
    // act: expect(page.locator('.status-badge')).toMatchSnapshot('unposted-badge.png')
    expect(true).toBe(true); // placeholder — Playwright visual spec
  });
});

// ─── RC-003 / CI-003: Create and Edit JE Header ──────────────────────────────
describe('RC-003 Create and Edit Journal Entry Header', () => {
  it('TC-FE-009: submit with empty required fields shows inline errors; save blocked', () => {
    // arrange: render JournalEntryForm mode="create"; all fields empty
    // act: fireEvent.click(screen.getByRole('button', { name: /save/i }))
    expect(screen.getByText('Company is required')).toBeInTheDocument();
    expect(screen.getByText('Journal entry type is required')).toBeInTheDocument();
    expect(screen.getByText('Transaction date is required')).toBeInTheDocument();
    expect(screen.getByText('Description is required')).toBeInTheDocument();
  });

  it('TC-FE-010: CompanyIdSelect disabled in edit mode; all fields read-only when status=Posted', () => {
    // arrange: render JournalEntryForm mode="edit" with unpostedJE
    // act: render form
    expect(screen.getByLabelText('Company ID')).toBeDisabled();
  });

  it('TC-FE-011: save form calls POST /journal-entries; callback receives journalId from response', async () => {
    // arrange: MSW mock POST → 201 { journalId: 42, journalNumber: 1001, status: 'Unposted' }
    // act: fill form + click save
    await waitFor(() => expect(screen.getByText('1001')).toBeInTheDocument());
  });

  it('TC-FE-012: full create JE e2e flow — fill form, save, see journalNumber + Unposted status', async () => {
    // arrange: Playwright e2e — app running
    // act: navigate to create; fill all required fields; click Save
    expect(true).toBe(true); // placeholder — Playwright e2e spec
  });

  it('TC-FE-013: inline errors linked via aria-describedby; focus moves to first error field; zero axe violations', async () => {
    // arrange: render JournalEntryForm mode="create"; submit empty
    // act: fireEvent.click(save button)
    expect(document.activeElement).toBe(screen.getByLabelText('Company ID'));
    expect(screen.getByLabelText('Company ID')).toHaveAttribute('aria-invalid', 'true');
  });
});

// ─── RC-004 / CI-004: Line Items Management ──────────────────────────────────
describe('RC-004 Journal Entry Line Items', () => {
  it('TC-FE-014: valid account code blur auto-populates accountDescription from GET /accounts/{code}', async () => {
    // arrange: MSW GET /accounts/US-01-1000-100-01 → { accountDescription: 'Cash - US Operations' }
    // act: type code into AccountCodeInput; fireEvent.blur(input)
    await waitFor(() => expect(screen.getByDisplayValue('Cash - US Operations')).toBeInTheDocument());
  });

  it('TC-FE-015: debit > 0 dims credit (opacity:0.5, pointer-events:none); credit > 0 dims debit; both 0 → neither dimmed', () => {
    // arrange: render LineItemRow; set debitAmount=100
    // act: check credit input styles
    expect(screen.getByLabelText('Credit Amount')).toHaveStyle({ opacity: '0.5', pointerEvents: 'none' });
  });

  it('TC-FE-016: add row appends row with next lineNumber; delete row removes it from grid', () => {
    // arrange: render LineItemsGrid with 2 lines
    // act: click Add Line; check 3 rows appear; click delete on row 2
    expect(screen.getAllByRole('row').length - 1).toBe(2); // header + 2 data rows after delete
  });

  it('TC-FE-017: account lookup populates description in < 500ms (MSW with 400ms delay)', async () => {
    // arrange: MSW with 400ms delay
    // act: type code + blur; measure time to description population
    const start = performance.now();
    await waitFor(() => screen.getByDisplayValue('Cash - US Operations'));
    expect(performance.now() - start).toBeLessThan(500);
  });

  it('TC-FE-018: grid has role="grid"; th elements have scope="col"; zero axe violations', async () => {
    // arrange: render LineItemsGrid with 3 rows
    // act: run axe-core
    expect(screen.getAllByRole('columnheader').every(th => th.getAttribute('scope') === 'col')).toBe(true);
  });
});

// ─── RC-005 / CI-005: Balance Validation Display ─────────────────────────────
describe('RC-005 Balance Validation Display', () => {
  it('TC-FE-019: adding debit line updates Total Debit immediately without save', () => {
    // arrange: render grid+footer; initial line debitAmount=500
    // act: add second line debitAmount=250
    expect(screen.getByTestId('total-debit').textContent).toBe('$750.00');
  });

  it('TC-FE-020: balanced (debits=credits) → difference $0.00; no unbalanced class', () => {
    // arrange: render LineItemsGridFooter with totalDebits=1435, totalCredits=1435
    expect(screen.getByTestId('difference-row').textContent).toContain('$0.00');
    expect(screen.getByTestId('difference-row')).not.toHaveClass('data-grid-difference-row--unbalanced');
  });

  it('TC-FE-021: unbalanced (debits≠credits) → difference shows non-zero + unbalanced class applied', () => {
    // arrange: render LineItemsGridFooter with totalDebits=1500, totalCredits=1435
    expect(screen.getByTestId('difference-row').textContent).toContain('$65.00');
    expect(screen.getByTestId('difference-row')).toHaveClass('data-grid-difference-row--unbalanced');
  });

  it('TC-FE-022: recalculation completes in < 100ms with 50 lines (performance NFR)', async () => {
    // arrange: grid with 50 lines
    // act: update one line; measure recalculation time
    const start = performance.now();
    // trigger update
    expect(performance.now() - start).toBeLessThan(100);
  });

  it('TC-FE-023: difference row has aria-live="polite"; sr-only "unbalanced" text present when unbalanced', () => {
    // arrange: render LineItemsGridFooter with totalDebits=1500, totalCredits=1435
    expect(screen.getByTestId('difference-row')).toHaveAttribute('aria-live', 'polite');
    expect(screen.getByText('unbalanced')).toHaveClass('sr-only');
  });
});

// ─── RC-006 / CI-006: Status and Audit Trail ─────────────────────────────────
describe('RC-006 Journal Entry Status and Audit Trail', () => {
  it('TC-FE-023: PostEntryButton disabled when isBalanced=false; click does not trigger onPost', () => {
    // arrange: render PostEntryButton with isBalanced=false
    expect(screen.getByRole('button', { name: /post/i })).toBeDisabled();
  });

  it('TC-FE-024: PostEntryButton hidden when status="Posted"; not in DOM', () => {
    // arrange: render PostEntryButton with status="Posted"
    expect(screen.queryByRole('button', { name: /post/i })).toBeNull();
  });

  it('TC-FE-025: audit fields (4) are read-only; typing does not change their values', () => {
    // arrange: render AuditFieldGroup with all 4 fields populated
    const editField = screen.getByLabelText('Edit Date/Time');
    expect(editField).toHaveAttribute('readonly');
  });

  it('TC-FE-026: click Post → POST /journal-entries/1/post → status becomes "Posted"; PostEntryButton removed', async () => {
    // arrange: MSW POST /journal-entries/1/post → 200 { status: 'Posted', postedDateTime: '...', posterUserId: 'Supervisor1' }
    // act: click PostEntryButton
    await waitFor(() => expect(screen.getByText('Posted')).toHaveClass('badge-posted'));
    expect(screen.queryByRole('button', { name: /post/i })).toBeNull();
  });

  it('TC-FE-027: status badge text "Unposted"/"Posted" visible to screen readers (not aria-hidden); zero axe violations', async () => {
    // arrange: render StatusBadge; run axe
    expect(screen.getByText('Unposted').getAttribute('aria-hidden')).not.toBe('true');
  });
});

// ─── RC-007 / CI-007: Record Navigation ──────────────────────────────────────
describe('RC-007 Record Navigation', () => {
  it('TC-FE-028: isFirst=true → First+Previous disabled; isLast=true → Next+Last disabled', () => {
    // arrange: render RecordNavigationToolbar with isFirst=true
    expect(screen.getByRole('button', { name: /first/i })).toBeDisabled();
    expect(screen.getByRole('button', { name: /previous/i })).toBeDisabled();
    expect(screen.getByRole('button', { name: /next/i })).not.toBeDisabled();
  });

  it('TC-FE-029: click Next → GET next JE → form updates with new journalNumber; no page reload', async () => {
    // arrange: MSW GET /journal-entries/1/navigation → { nextJournalId: 2 }; GET /journal-entries/2 → { journalNumber: 1002 }
    // act: click Next button
    await waitFor(() => expect(screen.getByDisplayValue('1002')).toBeInTheDocument());
  });

  it('TC-FE-030: all 4 navigation buttons have descriptive aria-label; zero axe violations', async () => {
    // arrange: render RecordNavigationToolbar; run axe
    const firstBtn = screen.getByRole('button', { name: /first journal entry/i });
    expect(firstBtn).toBeInTheDocument();
  });
});

// ─── RC-008 / CI-008: Company Selection ──────────────────────────────────────
describe('RC-008 Company and Entity Context Selection', () => {
  it('TC-FE-031: each option displays exactly "{companyId} - {companyName}" format', () => {
    // arrange: render CompanyIdSelect with 2 companies
    expect(screen.getByRole('option', { name: '0004 - 0004_company' })).toBeInTheDocument();
    expect(screen.getByRole('option', { name: '0005 - Alpha Corp' })).toBeInTheDocument();
  });

  it('TC-FE-032: disabled=true → select is disabled; disabled=false → onChange fires on selection', () => {
    // arrange: render CompanyIdSelect disabled=true
    expect(screen.getByRole('combobox')).toBeDisabled();
  });

  it('TC-FE-033: company list populates within 500ms of form load (MSW 400ms delay)', async () => {
    // arrange: MSW GET /reference/companies with 400ms delay
    const start = performance.now();
    await waitFor(() => expect(screen.getAllByRole('option').length).toBeGreaterThan(1));
    expect(performance.now() - start).toBeLessThan(500);
  });

  it('TC-FE-034: select labeled "Company ID"; keyboard accessible; zero axe violations', async () => {
    // arrange: render CompanyIdSelect in form context; run axe
    expect(screen.getByLabelText('Company ID')).toBeInTheDocument();
  });
});
